%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#   with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

name: 'Extract Spy++'

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: '*'

jobs:
  preinstalled_tainted:
    name: 'Identify the pre-installed (license-wise tainted) files'
    runs-on: windows-latest
    steps:
      - name: "Copy the Spy++ files that ship in GitHub's CI image"
        shell: bash
        run: |
          exec &> >(tee --append -- "$GITHUB_STEP_SUMMARY")
          echo '```text'

          FILES=(
            /c/Windows/System32/{dbghelp,msvcp140,vcruntime140}.dll
            '/c/Program Files/Microsoft Visual Studio'/*/*/*/Tools/spy*
            )
          du --apparent-size --bytes "${FILES[@]}"
          echo

          cp -nt . -- "${FILES[@]}"
          FILES=( "${FILES[@]##*/}" )

          for ALGO in md5 sha:{1,256,512}; do
            ( echo "# ${ALGO//:/} checksums:"
              "${ALGO//:/}"sum --binary -- "${FILES[@]}"
              echo
            ) | tee --append -- "cksums.${ALGO%%:*}"
          done

          echo '```'

      - uses: actions/upload-artifact@v6
        with:
          name: spypp_preinstalled_TAINTED
          path: .



  via_winget:
    runs-on: windows-latest
    env:
      WINGET_MSSTORE_REGION: DE
      OUT_DIR: '${{ github.workspace }}\output'
      VS_BASEDIR: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\'
    steps:
      - uses: actions/checkout@v6

      - name: 'Install Visual Studio Build Tools'
        shell: bash
        run: |
          # .\Start-StepSummaryTee.ps1
          mkdir -- output
          exec &> >(tee -- "$GITHUB_STEP_SUMMARY" output/stepsumm.log)
          echo '```text'
          PKG='Microsoft.VisualStudio.2022.BuildTools'
          VCT=(
            --quiet --wait --norestart
            --log '.\output\vsinstaller.log.txt'
            # --dry-run

            # Custom destination to hopefully make it independent from
            # the pre-installed Visual Studio in GitHub's VM image:
            --layout '.\output\vs-dbg'

            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
            )
          LOG_SED='
            # Do not clutter CI output with progress spinner animation:
            /^[\x00- \/\|\\-]*$/d
            '
          ( winget.exe install --exact --id "$PKG" \
            --verbose --disable-interactivity \
            --accept-package-agreements --accept-source-agreements \
            --override "${VCT[*]}" || echo "E: winget failed, rv=$?"
          ) |& tr '\r' '\n' | sed -re "$LOG_SED" | uniq
          echo
          echo 'Files in output:'
          ls -Al output
          echo "Step took $SECONDS sec."
          echo '```'

      - uses: actions/upload-artifact@v6
        with:
          name: spypp_via_winget
          path: output/







...
